/**
 * @type {ImagesCollection} imageCollections
 */

export const imageCollections = {
    animals: [
        {id: 1, name: "animal1", url: "../assets/images/animals/animal1.png"},
        {id: 2, name: "animal2", url: "../assets/images/animals/animal2.png"},
        {id: 3, name: "animal3", url: "../assets/images/animals/animal3.png"},
        {id: 4, name: "animal4", url: "../assets/images/animals/animal4.png"},
        {id: 5, name: "animal5", url: "../assets/images/animals/animal5.png"},
        {id: 6, name: "animal6", url: "../assets/images/animals/animal6.png"},
        {id: 7, name: "animal7", url: "../assets/images/animals/animal7.png"},
        {id: 8, name: "animal8", url: "../assets/images/animals/animal8.png"},

    ],
    fruits: [
        {id: 1, name: "fruit1", url: "../assets/images/fruits/fruit1.png"},
        {id: 2, name: "fruit2", url: "../assets/images/fruits/fruit2.png"},
        {id: 3, name: "fruit3", url: "../assets/images/fruits/fruit3.png"},
        {id: 4, name: "fruit4", url: "../assets/images/fruits/fruit4.png"},
        {id: 5, name: "fruit5", url: "../assets/images/fruits/fruit5.png"},
        {id: 6, name: "fruit6", url: "../assets/images/fruits/fruit6.png"},
        {id: 7, name: "fruit7", url: "../assets/images/fruits/fruit7.png"},
        {id: 8, name: "fruit8", url: "../assets/images/fruits/fruit8.png"},

    ],
    cars: [
        {id: 1, name: "car1", url: "../assets/images/cars/car1.png"},
        {id: 2, name: "car2", url: "../assets/images/cars/car2.png"},
        {id: 3, name: "car3", url: "../assets/images/cars/car3.png"},
        {id: 4, name: "car4", url: "../assets/images/cars/car4.png"},
        {id: 5, name: "car5", url: "../assets/images/cars/car5.png"},
        {id: 6, name: "car6", url: "../assets/images/cars/car6.png"},
        {id: 7, name: "car7", url: "../assets/images/cars/car7.png"},
        {id: 8, name: "car8", url: "../assets/images/cars/car8.png"},

    ],
    mario: [
        {id: 1, name: "mario1", url: "../assets/images/mario/mario1.png"},
        {id: 2, name: "mario2", url: "../assets/images/mario/mario2.png"},
        {id: 3, name: "mario3", url: "../assets/images/mario/mario3.png"},
        {id: 4, name: "mario4", url: "../assets/images/mario/mario4.png"},
        {id: 5, name: "mario5", url: "../assets/images/mario/mario5.png"},
        {id: 6, name: "mario6", url: "../assets/images/mario/mario6.png"},
        {id: 7, name: "mario7", url: "../assets/images/mario/mario7.png"},
        {id: 8, name: "mario8", url: "../assets/images/mario/mario8.png"},

    ],
    ghibli: [
        {id: 1, name: "ghibli1", url: "../assets/images/ghibli/ghibli1.png"},
        {id: 2, name: "ghibli2", url: "../assets/images/ghibli/ghibli2.png"},
        {id: 3, name: "ghibli3", url: "../assets/images/ghibli/ghibli3.png"},
        {id: 4, name: "ghibli4", url: "../assets/images/ghibli/ghibli4.png"},
        {id: 5, name: "ghibli5", url: "../assets/images/ghibli/ghibli5.png"},
        {id: 6, name: "ghibli6", url: "../assets/images/ghibli/ghibli6.png"},
        {id: 7, name: "ghibli7", url: "../assets/images/ghibli/ghibli7.png"},
        {id: 8, name: "ghibli8", url: "../assets/images/ghibli/ghibli8.png"},

    ],
    disney: [
        {id: 1, name: "disney1", url: "../assets/images/disney/disney1.png"},
        {id: 2, name: "disney2", url: "../assets/images/disney/disney2.png"},
        {id: 3, name: "disney3", url: "../assets/images/disney/disney3.png"},
        {id: 4, name: "disney4", url: "../assets/images/disney/disney4.png"},
        {id: 5, name: "disney5", url: "../assets/images/disney/disney5.png"},
        {id: 6, name: "disney6", url: "../assets/images/disney/disney6.png"},
        {id: 7, name: "disney7", url: "../assets/images/disney/disney7.png"},
        {id: 8, name: "disney8", url: "../assets/images/disney/disney8.png"},

    ],
    bde: [
        {id: 1, name: "bde1", url: "../assets/images/bde/bde1.png"},
        {id: 2, name: "bde2", url: "../assets/images/bde/bde2.png"},
        {id: 3, name: "bde3", url: "../assets/images/bde/bde3.png"},
        {id: 4, name: "bde4", url: "../assets/images/bde/bde4.png"},
        {id: 5, name: "bde5", url: "../assets/images/bde/bde5.png"},
        {id: 6, name: "bde6", url: "../assets/images/bde/bde6.png"},
        {id: 7, name: "bde7", url: "../assets/images/bde/bde7.png"},
        {id: 8, name: "bde8", url: "../assets/images/bde/bde8.png"},
    ],
    pokemon: [
        {id: 1, name: "pokemon1", url: "../assets/images/pokemon/pokemon1.png"},
        {id: 2, name: "pokemon2", url: "../assets/images/pokemon/pokemon2.png"},
        {id: 3, name: "pokemon3", url: "../assets/images/pokemon/pokemon3.png"},
        {id: 4, name: "pokemon4", url: "../assets/images/pokemon/pokemon4.png"},
        {id: 5, name: "pokemon5", url: "../assets/images/pokemon/pokemon5.png"},
        {id: 6, name: "pokemon6", url: "../assets/images/pokemon/pokemon6.png"},
        {id: 7, name: "pokemon7", url: "../assets/images/pokemon/pokemon7.png"},
        {id: 8, name: "pokemon8", url: "../assets/images/pokemon/pokemon8.png"},
    ],
    youtube: [
        {id: 1, name: "youtube1", url: "../assets/images/youtube/youtube1.png"},
        {id: 2, name: "youtube2", url: "../assets/images/youtube/youtube2.png"},
        {id: 3, name: "youtube3", url: "../assets/images/youtube/youtube3.png"},
        {id: 4, name: "youtube4", url: "../assets/images/youtube/youtube4.png"},
        {id: 5, name: "youtube5", url: "../assets/images/youtube/youtube5.png"},
        {id: 6, name: "youtube6", url: "../assets/images/youtube/youtube6.png"},
        {id: 7, name: "youtube7", url: "../assets/images/youtube/youtube7.png"},
        {id: 8, name: "youtube8", url: "../assets/images/youtube/youtube8.png"},
    ],
    icon: [
        {id: 1, name: "icon1", url: "../assets/images/icon/icon1.png"},
        {id: 2, name: "icon2", url: "../assets/images/icon/icon2.png"},
        {id: 3, name: "icon3", url: "../assets/images/icon/icon3.png"},
        {id: 4, name: "icon4", url: "../assets/images/icon/icon4.png"},
        {id: 5, name: "icon5", url: "../assets/images/icon/icon5.png"},
        {id: 6, name: "icon6", url: "../assets/images/icon/icon6.png"},
        {id: 7, name: "icon7", url: "../assets/images/icon/icon7.png"},
        {id: 8, name: "icon8", url: "../assets/images/icon/icon8.png"},
    ],
    top : [
        {id: 1, name: "top1", url: "../assets/images/top/top1.png"},
        {id: 2, name: "top2", url: "../assets/images/top/top2.png"},
        {id: 3, name: "top3", url: "../assets/images/top/top3.png"},
        {id: 4, name: "top4", url: "../assets/images/top/top4.png"},
        {id: 5, name: "top5", url: "../assets/images/top/top5.png"},
        {id: 6, name: "top6", url: "../assets/images/top/top6.png"},
        {id: 7, name: "top7", url: "../assets/images/top/top7.png"},
        {id: 8, name: "top8", url: "../assets/images/top/top8.png"},
    ],
    brands : [
        {id: 1, name: "brand1", url: "../assets/images/brands/brand1.png"},
        {id: 2, name: "brand2", url: "../assets/images/brands/brand2.png"},
        {id: 3, name: "brand3", url: "../assets/images/brands/brand3.png"},
        {id: 4, name: "brand4", url: "../assets/images/brands/brand4.png"},
        {id: 5, name: "brand5", url: "../assets/images/brands/brand5.png"},
        {id: 6, name: "brand6", url: "../assets/images/brands/brand6.png"},
        {id: 7, name: "brand7", url: "../assets/images/brands/brand7.png"},
        {id: 8, name: "brand8", url: "../assets/images/brands/brand8.png"},
    ],
    genshin : [
        {id: 1, name: "genshin1", url: "../assets/images/genshin/genshin1.png"},
        {id: 2, name: "genshin2", url: "../assets/images/genshin/genshin2.png"},
        {id: 3, name: "genshin3", url: "../assets/images/genshin/genshin3.png"},
        {id: 4, name: "genshin4", url: "../assets/images/genshin/genshin4.png"},
        {id: 5, name: "genshin5", url: "../assets/images/genshin/genshin5.png"},
        {id: 6, name: "genshin6", url: "../assets/images/genshin/genshin6.png"},
        {id: 7, name: "genshin7", url: "../assets/images/genshin/genshin7.png"},
        {id: 8, name: "genshin8", url: "../assets/images/genshin/genshin8.png"},
    ],
    knowns : [
        {id: 1, name: "known1", url: "../assets/images/knowns/known1.png"},
        {id: 2, name: "known2", url: "../assets/images/knowns/known2.png"},
        {id: 3, name: "known3", url: "../assets/images/knowns/known3.png"},
        {id: 4, name: "known4", url: "../assets/images/knowns/known4.png"},
        {id: 5, name: "known5", url: "../assets/images/knowns/known5.png"},
        {id: 6, name: "known6", url: "../assets/images/knowns/known6.png"},
        {id: 7, name: "known7", url: "../assets/images/knowns/known7.png"},
        {id: 8, name: "known8", url: "../assets/images/knowns/known8.png"},
    ]
};
